### PR TITLE
Use list-installed to get npm packages

### PR DESCRIPTION
**Pull request by DarthHater**
We've used read-installed to great success in AuditJS, etc..., and in looking out on the interwebs, there's now a `list-installed` which is more modern (cheers to @voxpelli for doing this!) and has types by default (yay!).

This PR would move from the old cruddy way of getting dependencies to a newer way influenced by AuditJS, etc...

It also drops dependency on `lodash` as a prod dependency, which is music to security checks ears.

Updates the `@types/node` dep to > 12 fwd, as 10 is no longer supported, and that type file was missing types that `list-installed` uses from `fs`.

### CODE REVIEW

**Review by ButterB0wl — APPROVED** [review]
looks good to me, can test when merged into the AWholeNewWorld branch

**Comment by voxpelli** [comment]
Happy that you found it useful 🙂

**Comment by ChurchRyan** [comment]
Hi @voxpelli!

**Comment by ChurchRyan** [comment]
Hi @voxpelli 

Thanks again for the awesome work. We would love to send you something as a token of our appreciation. Is the email listed on your profile a good one to use to get the ball rolling on that? 

Thanks!

**Comment by voxpelli** [comment]
@ChurchRyan Yes, pelle@kodfabrik.se

**Pull request merged**
