### PR TITLE
Get application specific config from a .sonatype-config file

### PR DESCRIPTION
**Pull request by DarthHater**
This is a quick lil ditty that allows for existence of a:

`.sonatype-config` file in the workspace root, that is of YAML file type, that has the following keys, under a `iq` key:

- `PublicApplication`
- `Stage`
- `Server`

Under an `application` key we also have:

- `IncludeDev`

That key is being used to specify if you want dev dependencies included or not (depending on the format, we may be able to support this!)

This pull request makes the following changes:
* Adds a `SonatypeConfig` type
* Checks for existence of `.sonatype-config` or `.sonatype-config.yaml` before each scan (so that you can switch repos, etc...) and changes the application ID, stage, and URL it is using based on this

An example yaml file for this looks like:

```
---
    iq:
        PublicApplication: testapp
        Stage: develop
        Server: http://localhost:8070
    application:
        IncludeDev: false
```

This will require doc updates, etc... as well

cc @bhamail / @DarthHater

### CODE REVIEW

**Review by ButterB0wl — COMMENTED** [review]
errors on compile:
image

**Comment by DarthHater** [comment]
@ButterB0wl that should be fixed now, some fun typescript stuff :)

**Review by ButterB0wl — CHANGES_REQUESTED** [review]
should add the IQ Server endpoint as a key as well

**Review by ButterB0wl — APPROVED** [review]
tested the config file for all the different stages, the url, and the app name and all is working as expected and overwrites the vals in the VSCode extension settings

**Review by ButterB0wl — APPROVED** [review]
Able to get results now with none of the fields filled out in the extension settings using the RC file and env vars for the user and token:
image

I tested in this project using the following RC file:
https://github.com/sonatype-nexus-community/cyclonedx-sbom-examples/blob/master/.sonatyperc

**Comment by DarthHater** [comment]
@ButterB0wl the file name is changed to `.sonatype-config`, you can give it another run through if you want!

**Review by ButterB0wl — APPROVED** [review]
Re-tested with the latest changes and everything is working as expected.  .sonatype-config file overrides anything in the settings.

**Review by ButterB0wl — APPROVED** [review]
Tested again and works for me with both a `.sonatype-config` and a `.sonatype-config.yaml` file

**Pull request merged**
